# Generated by Django 3.0.5 on 2020-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('title', models.TextField()),
                ('link', models.URLField(max_length=400)),
                ('subreddit', models.URLField(blank=True, max_length=400)),
            ],
        ),
    ]
